apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: kubernetes-master


# kubectl taint node <node name> <key or taint name:taint effect>
# kubectl taint node controlplane node-role.kubernetes.io/master:NoSchedule
